name: CodeQL Analysis and CMSIS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  cmsis-build:
    name: CMSIS Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1
  
      - name: Build
        run: |
          echo "Building Blinky example ..."
          cbuild Blinky.csolution.yml --packs --update-rte --context .debug+avh 
